changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - Breaking
    - title: 🚀 Enhancements
      labels:
        - Enhancement
    - title: 🐛 Bug Fixes
      labels:
        - Bugfix
