name: Report a Bug
description: Report unexpected behavior or broken functionality.
labels:
  - Potential Bug
body:
  - type: markdown
    attributes:
      value: >
        Thanks for opening a bug report! Please complete this form so the issue
        can be investigated.

  - type: input
    id: terms
    attributes:
      label: "🔎 Search Terms"
      description: >
        What search terms did you use when trying to find an existing bug
        report? List them here so people can find this one more easily.
      placeholder: "something, is, broken"
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: "📷 Version and Environment Information"
      description: "Tell us about your development environment."
      value: |
        -   Neotype Prelude version:
        -   TypeScript version:
        -   Node.js version:

        <!--
        If you have any configuration settings that you think may be relevant to
        this bug (tsconfig.json, package.json, etc.) please include them here!
        -->
    validations:
      required: true

  - type: textarea
    id: mre
    attributes:
      label: "💻 Minimal Reproducible Example"
      description: "Please demonstrate the behavior of the bug."
      placeholder: |
        Good examples:

        -   are short and consise.
        -   clearly communicate the incorrect behavior.
        -   do not include code or other external libraries that are unrelated
            to the bug.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "🐛 Actual Behavior"
      description: "What is the incorrect behavior, and why is it wrong?"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "🎯 Expected Behavior"
      description: "What should the correct behavior be, and why?"
    validations:
      required: true
