blank_issues_enabled: false
contact_links:
  - name: Request a New Feature
    url: https://github.com/jm4rtinez/neotype_instances/discussions
    about: Please open an "Idea" Discussion with your idea.
  - name: Ask a Question
    url: https://github.com/jm4rtinez/neotype_instances/discussions
    about: Please open a "Q&A" Discussion to ask a question or get help.
  - name: Get in Touch
    url: https://discord.gg/hpD6TCeMWT
    about: Join our Discord server to connect with the community in more ways!
