name: Change the Documentation
description: Request changes to the library's documentation.
labels:
  - Documentation
body:
  - type: dropdown
    id: change_type
    attributes:
      label: "👉 Type of Change"
      description: >
        Is this an addition, deletion, or revision to the documentation?
      options:
        - Addition
        - Deletion
        - Revision
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: "📝 Proposed Change"
      description: "What change are you proposing?"
      placeholder: |
        Examples:

        "Add a section about (...) in the (...) module"
        "Remove the stale docs for (...)"
        "Fix spelling errors in the descriptions for (...)"
        "Move the explanations for (...) from (...) to (...)"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "👍 Motivation"
      description: "Are there notable motivations for the change?"
      placeholder: |
        Examples:

        "There is currently no documentation for the (...) feature"
        "This would alleviate confusion from how to use (...)"
        "This would make the documentation friendlier for new users"
