name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run style

  test_node:
    name: Node.js @${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test -- --forbid-only --forbid-pending

  test_ts:
    name: TypeScript @${{ matrix.ts-version }}
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        ts-version:
          - ~4.7
          - ~4.8
          - ~4.9
          - next
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm i -D typescript@${{ matrix.ts-version }}
      - run: npm test -- --forbid-only --forbid-pending
